# Generated by Django 5.1.15 on 2026-09-10 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('DSL_SERVICE', 'DSL Service'), ('COPPER_PAIR', 'Copper Pair'), ('COMPLAINT', 'Complaint')], max_length=20),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_description', models.CharField(help_text="e.g. 'No dial tone', 'DSL not syncing'", max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('IRRELEVANT', 'Irrelevant')], default='OPEN', max_length=20)),
                ('assigned_to', models.CharField(blank=True, help_text='Assigned lineman/technician name', max_length=150)),
                ('resolution_notes', models.CharField(blank=True, max_length=500)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='customers.customer')),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['customer', '-reported_at'], name='customers_c_custome_f7fd65_idx'), models.Index(fields=['status'], name='customers_c_status_4b3e98_idx')],
            },
        ),
    ]
