# Generated by Django 5.1.15 on 2026-09-15 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_activitylog_entity_type_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_id',
            field=models.CharField(blank=True, help_text='ISP subscriber/user ID, e.g. lah9201640 — must be unique across all customers', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dslservice',
            name='modem_serial',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dslservice',
            name='msag_port',
            field=models.PositiveSmallIntegerField(help_text='Port number on the card, 0-63 (a DSL line card has 64 ports)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(63)]),
        ),
        migrations.AddIndex(
            model_name='dslservice',
            index=models.Index(fields=['msag', 'msag_card'], name='customers_d_msag_id_321af2_idx'),
        ),
        migrations.AddConstraint(
            model_name='dslservice',
            constraint=models.UniqueConstraint(fields=('msag', 'msag_card', 'msag_port'), name='unique_port_per_card'),
        ),
    ]
