# Generated by Django 5.1.15 on 2026-09-07 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, help_text='e.g. Admin, GOVT. COLLEGE OF TECHNOLOGY', max_length=200)),
                ('subscriber_type', models.CharField(choices=[('GOV', 'Government'), ('SEMI_GOV', 'Semi-Government')], default='GOV', max_length=20)),
                ('address_line', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone_primary', models.CharField(help_text='Landline / customer phone, e.g. 0559201351', max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user_id', models.CharField(blank=True, help_text='ISP subscriber/user ID, e.g. lah9201640', max_length=50)),
                ('tax_code', models.CharField(blank=True, max_length=50)),
                ('dept_code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='customers.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DSLService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsl_package', models.CharField(help_text="e.g. 'Broadband 8Mbps Unlimited'", max_length=100)),
                ('technology', models.CharField(choices=[('ADSL2+', 'ADSL2+'), ('VDSL2', 'VDSL2'), ('SHDSL', 'SHDSL')], default='ADSL2+', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('msag_card', models.CharField(help_text="MSAG card number, e.g. 'C04'", max_length=20)),
                ('msag_port', models.CharField(help_text="MSAG port number, e.g. 'P12'", max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('modem_serial', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('FAULTY', 'Faulty'), ('DECOMMISSIONED', 'Decommissioned')], default='ACTIVE', max_length=20)),
                ('status_reason', models.CharField(blank=True, max_length=255)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('last_fault_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dsl_service', to='customers.customer')),
            ],
            options={
                'ordering': ['customer__name'],
            },
        ),
        migrations.CreateModel(
            name='CopperPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_code', models.CharField(blank=True, help_text='Street cabinet / DP identifier', max_length=50)),
                ('pair_number', models.CharField(help_text="Copper pair number, e.g. '214'", max_length=20)),
                ('binder_group', models.CharField(blank=True, max_length=50)),
                ('distribution_point', models.CharField(blank=True, help_text='Pole/DP reference', max_length=100)),
                ('cable_length_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('DEGRADED', 'Degraded'), ('FAULTY', 'Faulty'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dsl_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='copper_pair', to='customers.dslservice')),
            ],
            options={
                'ordering': ['pair_number'],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('directorate', models.CharField(blank=True, help_text='e.g. Lahore Directorate (WO)', max_length=150)),
                ('sub_division', models.CharField(blank=True, help_text='e.g. DSL Lahore (WO)', max_length=150)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges', to='customers.city')),
            ],
            options={
                'verbose_name_plural': 'Exchanges',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MSAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='MSAG identifier / cabinet code', max_length=50)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='msags', to='customers.exchange')),
            ],
            options={
                'verbose_name': 'MSAG',
                'verbose_name_plural': 'MSAGs',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='dslservice',
            name='msag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dsl_services', to='customers.msag'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='customers.region'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_primary'], name='customers_c_phone_p_abd3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user_id'], name='customers_c_user_id_c1d57c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='msag',
            unique_together={('exchange', 'code')},
        ),
        migrations.AddIndex(
            model_name='dslservice',
            index=models.Index(fields=['status'], name='customers_d_status_42eea3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('region', 'name')},
        ),
    ]
