# Generated by Django 5.1.15 on 2026-09-09 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('entity_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('DSL_SERVICE', 'DSL Service'), ('COPPER_PAIR', 'Copper Pair')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], max_length=10)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('actor_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='customers_a_custome_f8ae12_idx'), models.Index(fields=['entity_type', 'entity_id'], name='customers_a_entity__319ccf_idx'), models.Index(fields=['-created_at'], name='customers_a_created_043e5f_idx'), models.Index(fields=['action'], name='customers_a_action_51376b_idx')],
            },
        ),
    ]
